Automations

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -22,7 +22,7 @@ jobs:
     - name: Install dependencies
       run: |
         sudo apt-get update
-        sudo apt-get install -y shellcheck
+        sudo apt-get install -y shellcheck jq
 
     - name: Setup Docker
       uses: docker/setup-buildx-action@v3
@@ -51,11 +51,72 @@ jobs:
         sudo ./bats-core/install.sh /usr/local
 
     - name: Deploy infrastructure
-      working-directory: terraform
-      run: terraform apply -auto-approve
+      run: | 
+	chmod +x scripts/deploy.sh
+	sudo scripts/deploy.sh --auto-install --non-interactive
 
     - name: Run Bash tests
       run: bats tests/
+
+    - name: Get exposed ports
+      run: |
+        terraform -chdir=terraform show -json \
+          | jq -r '.values.root_module.resources[]
+          | select(.type=="docker_container")
+          | .values.ports[].external' \
+          | sort -u > ports.txt
+
+    - name: Detect firewall
+      id: firewall
+      run: |
+        if command -v firewall-cmd >/dev/null 2>&1 && systemctl is-active --quiet firewalld; then
+          echo "type=firewalld" >> $GITHUB_OUTPUT
+        elif command -v ufw >/dev/null 2>&1; then
+          echo "type=ufw" >> $GITHUB_OUTPUT
+        else
+          echo "type=iptables" >> $GITHUB_OUTPUT
+        fi
+
+    - name: Verify firewall rules (firewalld)
+      if: steps.firewall.outputs.type == 'firewalld'
+      run: |
+        ports=$(cat ports.txt)
+
+        for port in $ports; do
+          echo "Checking firewalld rule for $port"
+          sudo firewall-cmd --list-ports | grep "${port}/tcp" || {
+            echo "Missing firewall rule for port $port"
+            exit 1
+          }
+        done
+
+    - name: Verify firewall rules (ufw)
+      if: steps.firewall.outputs.type == 'ufw'
+      run: |
+        ports=$(cat ports.txt)
+    
+        for port in $ports; do
+          echo "Checking UFW rule for $port"
+          sudo ufw status | grep "$port/tcp" || {
+            echo "Missing firewall rule for port $port"
+            exit 1
+          }
+        done
+
+    - name: Verify firewall rules (iptables)
+      if: steps.firewall.outputs.type == 'iptables'
+      run: |
+        ports=$(cat ports.txt)
+    
+        for port in $ports; do
+          echo "Checking iptables rule for $port"
+
+          sudo iptables -L INPUT -n | grep ":$port " || {
+            echo "Missing firewall rule for port $port"
+            exit 1
+          }
+        done
+
 
     - name: Destroy infrastructure
       working-directory: terraform
